### ISSUE TITLE
Use a better format for sources and exports

### ISSUE THREAD

**Issue by solstag** [amchagas/open-hardware-supply#9]
Ni! In connection with https://github.com/amchagas/open-hardware-supply/issues/5#issuecomment-774571074, as we'll probably collect our sources again:

Bibtex is not the best format for bibliographic data exchange, it's meant for presentation using Latex, not for data processing.

All of Wos and Scopus and Zotero can directly export to CSV, but also to the de-facto standard RIS format, which can be consumed with, e.g., https://pypi.org/project/rispy/

So if we're to produce our sources again, we should have them as RIS (sometimes refered to as Endnote or CIW) files.

Cheers! @amchagas 
.~´

**Comment by amchagas** [comment]
Hi! 
Thanks @solstag, again this is one of those things that I did, because I did not know any better... 
So from what I am understanding, next steps here would be:
- do another search using the new query you mentioned in #5 
- export them as RIS format
- filter using the code we already have
- either have a manual search through a set number of papers to see in this subsample which ones have repositories/design files available, or use the plos collection as a benchmark - or maybe both as the plos collection might not have enough data to be statistically significant for this new dataset?
- once that is all cleaned up and checked for, move forward into writing a bit more..

**Comment by amchagas** [comment]
related, I cannot seem to find a way to export WoS to RIS. 
Options include Endnote desktop or CSV files...I exported both just in case. They live now in `data/sources`

**Comment by solstag** [comment]
Excellent !
Did you run the script to get the query? eheh
For WoS, it was indeed the Endnote option (answer was in OP).

**Comment by amchagas** [comment]
oh, only seeing the question about Scielo now...
Using scielo.org to search and export data... is there a better resource?

**Comment by solstag** [comment]
Ni! No, that's great, I just wanted to learn from you how you did it.
I opened https://scielo.br and didn't realize that it's legacy website, hence my question.
Also, closing this issue since we're now using RIS for these sources =D
